apiVersion: v1
kind: ServiceAccount
metadata:
  name: appdynamics-cluster-agent
  namespace: appdynamics
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: appdynamics-cluster-agent
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
      - pods/exec
      - endpoints
      - persistentvolumeclaims
      - resourcequotas
      - nodes
      - events
      - namespaces
      - services
      - configmaps
      - secrets
    verbs:
      - get
      - watch
      - list
      - create
      - update
      - patch
      - delete
      - deletecollection
  - apiGroups:
      - apps
    resources:
      - daemonsets
      - statefulsets
      - deployments
      - replicasets
    verbs:
      - get
      - watch
      - list
      - create
      - update
      - patch
      - delete
      - deletecollection
  - apiGroups:
      - "batch"
      - "extensions"
    resources:
      - "jobs"
    verbs:
      - "get"
      - "list"
      - "watch"
      - create
      - update
      - patch
      - delete
      - deletecollection
  - apiGroups:
      - metrics.k8s.io
    resources:
      - pods
      - nodes
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
      - deletecollection
  - apiGroups:
      - appdynamics.com
    resources:
      - '*'
      - clusteragents
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
      - deletecollection
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: appdynamics-cluster-agent
subjects:
  - kind: ServiceAccount
    name: appdynamics-cluster-agent
    namespace: appdynamics
roleRef:
  kind: ClusterRole
  name: appdynamics-cluster-agent
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: appdynamics.com/v1alpha1
kind: Clusteragent
metadata:
  name: ad-air-cluster-agent
  namespace: appdynamics
spec:
  controllerUrl: "http://192.168.2.100:8090"
  account: "customer1"
  appName: "AD-Air"
  serviceAccountName: appdynamics-cluster-agent
  logLevel: "INFO"
  stdoutLogging: "true"
  instrumentationMethod: Env
  nsToInstrumentRegex: gcp-appd-apm|teastore
  appNameStrategy: label
  appNameLabel: appdAppName
  defaultAppName: "Noname-App"
  instrumentationRules:
  - namespaceRegex: gcp-appd-apm|teastore
    labelMatch:
    - instrument: appd-auto
    appNameLabel: appdAppName
    netvizInfo:
      bciEnabled: true
      port: 3892

    #tierName: - use deployment name by default
  nsToMonitor: [appdynamics,default,ad-air-appd-apm,gcp-appd-apm,teastore]
